# GitHub Pages Configuration
title: "VotersSpeak - Executive Branch Contacts"
description: "Contact President Biden, VP Harris, and other executive officials"
baseurl: ""
url: "https://maxmcgillvo.github.io/votersspeak.com"